---
version: '2'
services:

  s3:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - ./src/test/resources/storage/minio:/data
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /data